### ISSUE TITLE
playback control API?

### ISSUE THREAD

**Issue by maks** [funkyfourier/spitback#1]
@funkyfourier I can see in the documentation that there is a `onpause` message the host can send to stop playback, but I can't see how to initially or after a onpause start playback?
I actually initially thought the the host completely drives playback but the presence of `bpm` and the `libpdhost-tick` makes me think that its Spitback itself that has a clock that the host should listen to and that then hosts sequencer should sync to, hence the question about how to essentially start that clock?

**Comment by funkyfourier** [comment]
The `onpause` patch is intended for use with the Android lifecycle API, ergo when the host app loses focus, exits etc. As you can see it basically just stops all notes, turns down the volume etc.

If you take a look at the `pd ticks` sub patch, there is a `timerstart` and `timerstop` receiver. These are the ones to call to start and stop the clock. The host can then, via the libpd receiveFloat method, receive notifications on when the "tick" events occur. In (for example) Sputter, on each of these ticks it calls back to Spitback telling it which notes to play.

So, yes, you are right about Spitback being the one doing the timing. The reason for that is that it generates the audio, so it makes sense for it to be done here.

BTW Spitback "ticks" are 1/16th of a measure. The are not to be confused with "ticks" used internally in Pure Data.

**Comment by maks** [comment]
@funkyfourier  thank you for such a quick response! 

Sorry, my fault, I completely missed seeing the `timerstart` and `timerstop` receivers inside `pd ticks`. And thanks for the detailed explanation, that all makes sense and yes `onpauses`'s naming should have rung a bell that it matched up to the lifecycle callback.

Luckily for me, my sequencer code is already using 1/16th's as the Fire has a 16x4 pad grid.
